#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99
STOP=01

start_service() {
    procd_open_instance
    procd_set_param command /root/passwall2-led-v6/engine.sh
    procd_set_param respawn 3600 5 0
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    rm -f /tmp/passwall_cache /tmp/passwall_lock /tmp/passwall_state
}
